# Generated by Django 4.2.6 on 2023-10-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='add_task',
        ),
    ]
