# Generated by Django 4.2.6 on 2023-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_rename_task_add_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
