# Generated by Django 4.2.6 on 2023-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_add_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='id',
            field=models.PositiveIntegerField(default=38, primary_key=True, serialize=False),
        ),
    ]
