# Generated by Django 4.2.6 on 2023-10-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_add_task_options_alter_add_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='id',
            field=models.PositiveIntegerField(default=910, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.CharField(default=b'#\xe6e\xd4\xaf\x08\x0f\xdf\x15\xc2\xb5\x10\xc1\xe8\xc8,\xe4\x0bI\xc3I\xc2=\xf3\xdb\xd7\xae\xbaQ\xd6', max_length=35, primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.add_task')),
            ],
        ),
    ]
