# Generated by Django 4.2.6 on 2023-10-25 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_add_task_id_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='add_task',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.todo'),
        ),
        migrations.AlterField(
            model_name='add_task',
            name='id',
            field=models.PositiveIntegerField(default=382, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.PositiveIntegerField(default=2589, primary_key=True, serialize=False),
        ),
    ]
